name: Docker Build and Push

on:
  workflow_dispatch:  # 添加手动触发
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io  # 使用Docker Hub
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAMESPACE: ${{ secrets.DOCKER_HUB_USERNAME }}  # 你的Docker Hub用户名或组织名

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Docker image tags
        id: get-tags
        run: |
          # 扫描docker目录下的所有文件夹名作为tag
          TAGS=""
          for dir in docker/*; do
            if [ -d "$dir" ]; then
              tag=$(basename "$dir")
              TAGS="${TAGS}${IMAGE_NAMESPACE}/${IMAGE_NAME}:${tag},"
            fi
          done
          # 移除最后的逗号
          TAGS=${TAGS%,}
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 为每个找到的Dockerfile构建并推送镜像
      - name: Build and push Docker images
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.get-tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
